#
# macros
#
[macros.install]
    prefix = ["sudo", "apt-get", "install", "-y", "--force-yes"]

# Not implemented
[macros.install__mac]
    prefix = ["INVALID_COMMAND", "ABORT"]

[macros.clone]
    prefix = ["git", "clone"]

#
# languages
#

[tasks.python]
    cmds = [["@install", "python-dev", "python-pip"]]

#
# vim plugins
#
[tasks.vim_plugin_ag]
    cmds = [
        ["wget", "http://swiftsignal.com/packages/ubuntu/precise/the-silver-searcher_0.14-1_amd64.deb"],
        ["dpkg", "-i", "the-silver-searcher_0.14-1_amd64.deb"],
        ["pwd"],
        ["rm", "the-silver-searcher_0.14-1_amd64.deb"],
    ]

#
# tools
#
#
[tasks.input]
    links = [["${HM_DEST}/.inputrc", "inputrc"]]

[tasks.bash]
    deps = ["bash__common"]
    links = [["${HM_DEST}/.bashrc", "bashrc"]]
[tasks.bash__mac]
    deps = ["bash__common"]
    links = [["${HM_DEST}/.bashrc", "bashrc__mac"]]
[tasks.bash__common]
    links = [["${HM_DEST}/.bash_aliases", "bash_aliases"]]

[tasks.git]
    cmds = [["@install", "git"]]
    links = [["${HM_DEST}/.gitconfig", "gitconfig"]]

[tasks.tmux]
    cmds = [["@install", "tmux"]]
    links = [["${HM_DEST}/.tmux.conf", "tmux.conf"]]

[tasks.tmux__mac]
    links = [["${HM_DEST}/.tmux.conf", "tmux.conf__mac"]]

[tasks.tmux_powerline]
    cmds = [
        ["wget", "https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf", "https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf"],
        ["install", "fontconfig"],
        ["mv", "PowerlineSymbols.otf", "/usr/share/fonts/"],
        ["fc-cache", "-vf"],
        ["mv", "10-powerline-symbols.conf", "/etc/fonts/conf.d/"],
    ]

[tasks.vimrc]
    links = [["${HM_DEST}/.vimrc", "vimrc"]]

[tasks.vim_upgrade]
    cmds = [
        ["add-apt-repository", "ppa:nmi/vim-snapshots"],
        ["apt-get", "update"],
        ["@install", "vim"],
    ]

[tasks.vim_complete]
    deps = ["vim_extra"]
    cmds = [["@install", "cmake", "g++"]]
 
[tasks.vim_extra]
    deps = ["vim", "vim_plugin_ag"]
    cmds = [["@install", "exuberant-ctags", "cscope"]]

[tasks.vim]
    deps = ["git", "vimrc"]
    cmds = [
        ["@install", "vim", "bash-completion", "python-dev"],
        ["@clone", "https://github.com/gmarik/vundle.git", "${HM_DEST}/.vim/bundle/vundle"],
        ["vim", "+BundleInstall", "+qall"],
    ]

#
# high level tasks
#

[tasks.default]
    deps = ["input", "bash", "git", "tmux", "vim"]
